variable "odineyes_account_id" {
  description = "The AWS account ID of the Odineyes platform that will assume this role"
  type        = string
  validation {
    condition     = can(regex("^\\d{12}$", var.odineyes_account_id))
    error_message = "odineyes_account_id must be a 12-digit AWS account ID."
  }
}

variable "external_id" {
  description = "The unique external ID generated by the Odineyes API for this account"
  type        = string
}

variable "role_name" {
  description = "Name of the IAM role to create"
  type        = string
  default     = "OdineyesReadOnly"
}

variable "policy_mode" {
  description = "Which policy mode to use: 'managed' (SecurityAudit + ViewOnlyAccess) or 'least-privilege' (inline policy)"
  type        = string
  default     = "managed"
  validation {
    condition     = contains(["managed", "least-privilege"], var.policy_mode)
    error_message = "policy_mode must be either 'managed' or 'least-privilege'."
  }
}

variable "least_privilege_policy_json" {
  description = "The JSON policy document to use when policy_mode is 'least-privilege'. Ignore if using 'managed'."
  type        = string
  default     = "{}"
}

variable "odineyes_api_url" {
  description = "URL of your Odineyes API (e.g. https://api.odineyes.com)"
  type        = string
}

variable "odineyes_api_key" {
  description = "API Key generated by Odineyes for auto-connecting this account"
  type        = string
  sensitive   = true
}

variable "odineyes_api_secret" {
  description = "API Secret generated by Odineyes for auto-connecting this account"
  type        = string
  sensitive   = true
}

variable "odineyes_scanner_ip_cidrs" {
  description = "List of allowed source IP CIDRs for Odineyes scanners. If provided, limits role assumption to these IPs."
  type        = list(string)
  default     = []
}
