"""Tetragon Event Shipper for Odineyes.

This lightweight agent reads JSON logs generated by Cilium Tetragon,
normalizes them into the Odineyes runtime schema, and batches them
to the backend API.
"""

import json
import os
import stat
import time
import urllib.request
import urllib.error
import logging

logger = logging.getLogger("tetragon_shipper")

def exe_mode_of(path: str | None) -> str:
    """Helper to check if a binary is SUID (used in test cases)."""
    if not path or not os.path.exists(path):
        return ""
    try:
        st = os.stat(path)
        if st.st_mode & stat.S_ISUID:
            return "SUID"
    except OSError:
        pass
    return ""

def normalize_for_detection(event: dict) -> dict:
    """Normalize a raw sensor event into the format the detection engine expects."""
    # This was originally for BCC; we're adapting it to handle Tetragon-like or normalized
    # event dicts so our tests don't break, while allowing Tetragon structures.
    # We will map standard Odineyes fields if present, else fallback.
    
    et = event.get("event_type", "")
    syscall = event.get("syscall", "")
    
    # Execve events
    if syscall == "execve" or "process_exec" in event:
        det = {
            "type": "execve",
            "comm": event.get("comm", ""),
            "parent_comm": event.get("parent", ""),
            "args": []
        }
        cmd = event.get("command", "")
        if cmd:
            det["args"] = cmd.split()
        return det

    # Connect events
    func_name = event.get("process_kprobe", {}).get("function_name", "")
    if syscall == "connect" or func_name == "tcp_connect":
        det = {
            "type": "connect",
            "comm": event.get("comm", ""),
            "parent_comm": event.get("parent", ""),
            "dst_ip": "",
            "dst_port": 0
        }
        dest = event.get("process_kprobe", {}).get("dest", "") or event.get("dest", "")
        if dest and ":" in dest:
            ip, port = dest.rsplit(":", 1)
            det["dst_ip"] = ip
            try:
                det["dst_port"] = int(port)
            except ValueError:
                pass
        return det

    # Mmap events (Fileless execution)
    if syscall == "mmap":
        return {
            "type": "mmap",
            "comm": event.get("comm", ""),
            "parent_comm": event.get("parent", ""),
            "prot_exec": event.get("prot_exec", False),
            "prot_write": event.get("prot_write", False),
            "map_anonymous": event.get("map_anonymous", False),
        }
        
    # Openat events
    if syscall == "openat" or (event.get("function_name") in ("sys_openat", "do_sys_open")):
        return {
            "type": "openat",
            "comm": event.get("comm", ""),
            "parent_comm": event.get("parent", "")
        }

    return {"type": "unknown"}

def parse_tetragon_event(line: str) -> dict | None:
    """Parse a single line of Tetragon JSON into Odineyes's ingestion format."""
    try:
        raw = json.loads(line)
    except json.JSONDecodeError:
        return None

    # We map Tetragon events to the fields expected by server.py / RuntimeEventRepository
    event_type = "runtime_event"
    comm = ""
    filename = ""
    pid = None
    workload = "host"
    summary = ""
    severity = "info"

    # Tetragon Exec
    if "process_exec" in raw:
        exec_ev = raw["process_exec"]
        proc = exec_ev.get("process", {})
        comm = proc.get("binary", "").split("/")[-1]
        filename = proc.get("arguments", "")
        pid = proc.get("pid")
        workload = proc.get("pod", {}).get("name", "host")
        event_type = "process_execution"
        summary = f"Process {comm} executed"
        parent_binary = exec_ev.get("parent", {}).get("binary", "")
        if parent_binary:
            raw["parent"] = parent_binary.split("/")[-1]
        raw["comm"] = comm
        
    # Tetragon Kprobe (Network / File)
    elif "process_kprobe" in raw:
        kprobe = raw["process_kprobe"]
        proc = kprobe.get("process", {})
        comm = proc.get("binary", "").split("/")[-1]
        pid = proc.get("pid")
        workload = proc.get("pod", {}).get("name", "host")
        func = kprobe.get("function_name", "")
        parent_binary = kprobe.get("parent", {}).get("binary", "")
        if parent_binary:
            raw["parent"] = parent_binary.split("/")[-1]
        raw["comm"] = comm
        
        if func == "tcp_connect":
            event_type = "network_connection"
            # Extract IP/port from args if available
            summary = f"Process {comm} initiated network connection"
        elif func == "sys_openat" or func == "do_sys_open":
            event_type = "file_access"
            filename = kprobe.get("args", [{}])[0].get("string_arg", "")
            summary = f"Process {comm} accessed {filename}"

    if not comm:
        return None

    return {
        "event_type": event_type,
        "comm": comm,
        "filename": filename,
        "pid": pid,
        "workload": workload,
        "summary": summary,
        "severity": severity,
        "node": "tetragon-node",
        "raw": raw
    }

def ship_events(api_url: str, events: list[dict], tenant_id: str):
    url = f"{api_url.rstrip('/')}/api/internal/runtime-events/batch"
    body = {
        "host_id": "tetragon-node",
        "events": events,
        "batch_id": str(time.time()),
        "batch_ts": time.time()
    }
    
    req = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        method="POST",
        headers={
            "Content-Type": "application/json",
            "x-tenant-id": tenant_id
        }
    )
    
    try:
        with urllib.request.urlopen(req) as resp:
            resp.read()
    except Exception as e:
        logger.error(f"Failed to ship events: {e}")

def main():
    log_file = os.environ.get("TETRAGON_LOG_PATH", "/var/run/cilium/tetragon/tetragon.log")
    api_url = os.environ.get("ODINEYES_API_URL", "http://localhost:8000")
    tenant_id = os.environ.get("ODINEYES_TENANT_ID", "default")
    
    batch = []
    
    if not os.path.exists(log_file):
        logger.error(f"Tetragon log file not found: {log_file}")
        return

    with open(log_file, "r") as f:
        # Go to the end of the file to tail new events
        f.seek(0, os.SEEK_END)
        while True:
            line = f.readline()
            if not line:
                if batch:
                    ship_events(api_url, batch, tenant_id)
                    batch = []
                time.sleep(1)
                continue
            
            ev = parse_tetragon_event(line)
            if ev:
                batch.append(ev)
                
            if len(batch) >= 50:
                ship_events(api_url, batch, tenant_id)
                batch = []

if __name__ == "__main__":
    main()
