"""CIS AWS End User Compute Services Benchmark v1.2.0 — full control catalog (2025-07-01).


Generated by scripts/generate_cis_catalogs.py from the locally extracted
benchmark text (euc-v1.2.txt). Reproduce with:

    python scripts/generate_cis_catalogs.py

Only factual control identifiers, titles, profile levels and the section
tree are reproduced; CIS's copyrighted rationale/audit/remediation prose
is NOT included. Controls mapped in CHECK_MAP auto-assess from real
CheckRegistry checks; the rest surface as not_assessed (Manual).
"""

from __future__ import annotations

from typing import Any

# (control_id, title, profile_level, section). Sections match the
# platform-wide labels in compliance_mapper so aggregation stays consistent.
_CONTROLS: list[tuple[str, str, int, str]] = [
    ("2.1", "Ensure Administration of WorkSpaces is defined using IAM", 1, "Compute"),
    ("2.2", "Ensure MFA is enabled for WorkSpaces users", 1, "Compute"),
    ("2.3", "Ensure WorkSpace volumes are encrypted", 1, "Compute"),
    ("2.4", "Ensure WorkSpaces are deployed in their own virtual private cloud (VPC)", 1, "Compute"),
    ("2.5", "Ensure WorkSpaces traffic is controlled and routed through a NAT Gateway", 1, "Compute"),
    ("2.6", "Ensure Web Access to Workspaces is Disabled", 1, "Compute"),
    ("2.7", "Ensure access is limited to trusted devices", 1, "Compute"),
    ("2.8", "Ensure the default IP access control group is disassociated", 1, "Compute"),
    ("2.9", "Ensure CloudWatch is set up for WorkSpaces", 1, "Compute"),
    ("2.10", "Ensure that patches and updates are performed on the operating system for Workstations", 1, "Compute"),
    ("2.11", "Ensure your WorkSpaces image has the appropriate CIS Operating System Benchmark applied", 1, "Compute"),
    ("2.12", "Restrict WorkSpaces Bundle options to organization approved versions", 1, "Compute"),
    ("2.13", "Ensure Workspaces images are not older than 90 days", 1, "Compute"),
    ("2.14", "Ensure WorkSpaces that are not being utilized are removed", 1, "Compute"),
    ("2.15", "Ensure primary interface ports for Workspaces are not open to all inbound traffic", 1, "Compute"),
    ("2.16", "Ensure FIPS Endpoint encryption is enabled for WorkSpaces", 1, "Compute"),
    ("2.17", "Ensure WorkSpaces API requests flow through a VPC Endpoint", 1, "Compute"),
    ("2.18", "Ensure Radius server is using the recommended security protocol", 1, "Compute"),
    ("3.1", "Ensure User Access Logging is enabled", 1, "Logging"),
    ("4.1", "Ensure Administrators of WorkDocs is defined using IAM", 1, "Storage"),
    ("4.2", "Ensure MFA is enabled for WorkDoc users", 1, "Storage"),
    ("4.3", "Ensure Workdocs access is limited to a range of allowable IP addresses", 1, "Storage"),
    ("4.4", "Utilize site wide activity feed for monitoring", 1, "Storage"),
    ("4.5", "Ensure new users can only be invited from allowed domains", 1, "Storage"),
    ("4.6", "Ensure only specific users are allowed to invite external users", 1, "Storage"),
    ("4.7", "Ensure publicly shareable links is not allowed in WorkDocs", 1, "Storage"),
    ("4.8", "Ensure any user that has not accessed WorkDocs in 30 days is set to inactive", 1, "Storage"),
    ("5.1", "Ensure AppStream is utilizing its own virtual private cloud (VPC)", 1, "Compute"),
    ("5.2", "Ensure a VPC Endpoint is set for AppStream", 1, "Compute"),
    ("5.3", "Ensure maximum session duration is no longer than 10 hours", 1, "Compute"),
    ("5.4", "Ensure session disconnect timeout is set to 5 minutes or less", 1, "Compute"),
    ("5.5", "Ensure session Idle disconnect timeout is set to 10 minutes or less", 1, "Compute"),
    ("5.6", "Ensure internet access is granted and managed through your VPC", 1, "Compute"),
    ("5.7", "Ensure Operating system updates are applied to your base image every 30 days", 1, "Compute"),
]

# Control → CheckRegistry check-id overlay, merged at score/SoA time.
CHECK_MAP: dict[str, list[str]] = {
}

def merge_check_map(ctrl_checks: dict[str, set]) -> None:
    """Merge CHECK_MAP into a {control_id: set(check_ids)} map, in place."""
    for ctrl, cids in CHECK_MAP.items():
        ctrl_checks.setdefault(ctrl, set()).update(cids)

def _build() -> dict[str, Any]:
    return {cid: {"title": title, "section": section, "level": level}
            for cid, title, level, section in _CONTROLS}

CIS_AWS_EUC: dict[str, Any] = _build()

def _demo() -> None:
    cat = CIS_AWS_EUC
    assert len(cat) == 34, len(cat)
    for ctrl in CHECK_MAP:
        assert ctrl in cat, ctrl
    print(f"cis_aws_euc_catalog self-check passed: {len(cat)} controls, "
          f"{len(CHECK_MAP)} auto-assessed")

if __name__ == "__main__":
    _demo()
