"""CIS AWS Compute Services Benchmark v2.0.0 — full control catalog (2026-06-26).


Generated by scripts/generate_cis_catalogs.py from the locally extracted
benchmark text (compute-v2.txt). Reproduce with:

    python scripts/generate_cis_catalogs.py

Only factual control identifiers, titles, profile levels and the section
tree are reproduced; CIS's copyrighted rationale/audit/remediation prose
is NOT included. Controls mapped in CHECK_MAP auto-assess from real
CheckRegistry checks; the rest surface as not_assessed (Manual).
"""

from __future__ import annotations

from typing import Any

# (control_id, title, profile_level, section). Sections match the
# platform-wide labels in compliance_mapper so aggregation stays consistent.
_CONTROLS: list[tuple[str, str, int, str]] = [
    ("2.1.1", "Ensure Consistent Naming Convention is used for Organizational AMI", 1, "Compute"),
    ("2.1.2", "Ensure Amazon Machine Images (AMIs) are encrypted", 1, "Compute"),
    ("2.1.3", "Ensure Only Approved Amazon Machine Images (AMIs) are Used", 1, "Compute"),
    ("2.1.4", "Ensure Images (AMI) are not older than 90 days", 1, "Compute"),
    ("2.1.5", "Ensure Images are not Publicly Available", 1, "Compute"),
    ("2.2.1", "Ensure EBS volume encryption is enabled", 1, "Compute"),
    ("2.2.2", "Ensure Public Access to EBS Snapshots is Disabled", 1, "Compute"),
    ("2.2.3", "Ensure EBS volume snapshots are encrypted", 1, "Compute"),
    ("2.2.4", "Ensure unused EBS volumes are removed", 1, "Compute"),
    ("2.2.5", "Ensure attached EBS volumes are encrypted", 1, "Compute"),
    ("2.3", "Ensure Tag Policies are Enabled", 1, "Compute"),
    ("2.4", "Ensure an Organizational EC2 Tag Policy has been Created", 1, "Compute"),
    ("2.5", "Ensure no AWS EC2 Instances are Older than 180 days", 1, "Compute"),
    ("2.6", "Ensure detailed monitoring is enable for production EC2 Instances", 1, "Compute"),
    ("2.7", "Ensure Default EC2 Security groups are not being used", 1, "Compute"),
    ("2.8", "Ensure the Use of IMDSv2 is Enforced on All Existing Instances", 1, "Compute"),
    ("2.9", "Ensure use of AWS Systems Manager to manage EC2 instances", 1, "Compute"),
    ("2.10", "Ensure unused ENIs are removed", 1, "Compute"),
    ("2.11", "Ensure instances stopped for over 90 days are removed", 1, "Compute"),
    ("2.12", "Ensure EBS volumes attached to an EC2 instance is marked for deletion upon instance termination", 1, "Compute"),
    ("2.13", "Ensure Secrets and Sensitive Data are not stored directly in EC2 User Data", 1, "Compute"),
    ("2.14", "Ensure EC2 Auto Scaling Groups Propagate Tags to EC2 Instances that it launches", 1, "Compute"),
    ("3.1", "Ensure Amazon ECS task definitions using 'host' network mode do not allow privileged or root user access to the host", 1, "Compute"),
    ("3.2", "Ensure 'assignPublicIp' is set to 'DISABLED' for Amazon ECS services", 1, "Compute"),
    ("3.3", "Ensure Amazon ECS task definitions do not have 'pidMode' set to 'host'", 1, "Compute"),
    ("3.4", "Ensure Amazon ECS task definitions do not have 'privileged' set to 'true'", 1, "Compute"),
    ("3.5", "Ensure 'readonlyRootFilesystem' is set to 'true' for Amazon ECS task definitions", 1, "Compute"),
    ("3.6", "Ensure secrets are not passed as container environment variables in Amazon ECS task definitions", 1, "Compute"),
    ("3.7", "Ensure logging is configured for Amazon ECS task definitions", 1, "Compute"),
    ("3.8", "Ensure Amazon ECS Fargate services are using the latest Fargate platform version", 1, "Compute"),
    ("3.9", "Ensure monitoring is enabled for Amazon ECS clusters", 1, "Compute"),
    ("3.10", "Ensure Amazon ECS services are tagged", 1, "Compute"),
    ("3.11", "Ensure Amazon ECS clusters are tagged", 1, "Compute"),
    ("3.12", "Ensure Amazon ECS task definitions are tagged", 1, "Compute"),
    ("3.13", "Ensure only trusted images are used with Amazon ECS", 1, "Compute"),
    ("3.14", "Ensure 'assignPublicIp' is set to 'DISABLED' for Amazon ECS task sets", 1, "Compute"),
    ("3.15", "Ensure ECS task definitions use awsvpc network mode", 1, "Compute"),
    ("3.16", "Ensure ECS Exec sessions have audit logging enabled", 1, "Compute"),
    ("5.1", "Apply updates to any apps running in Lightsail", 1, "Compute"),
    ("5.2", "Change default Administrator login names and passwords for applications", 1, "Compute"),
    ("5.3", "Disable SSH and RDP ports for Lightsail instances when not needed", 1, "Compute"),
    ("5.4", "Ensure SSH is restricted to only IP address that should have this access", 1, "Networking"),
    ("5.5", "Ensure RDP is restricted to only IP address that should have this access", 1, "Networking"),
    ("5.6", "Disable IPv6 Networking if not in use within your organization", 1, "Compute"),
    ("5.7", "Ensure you are using an IAM policy to manage access to buckets in Lightsail", 1, "Compute"),
    ("5.8", "Ensure Lightsail instances are attached to the buckets", 1, "Compute"),
    ("5.9", "Ensure that your Lightsail buckets are not publicly accessible", 1, "Compute"),
    ("5.10", "Enable storage bucket access logging", 1, "Compute"),
    ("5.11", "Ensure your Windows Server based lightsail instances are updated with the latest security patches", 1, "Compute"),
    ("5.12", "Change the auto-generated password for Windows based instances", 1, "Compute"),
    ("6.1", "Ensure you are using VPC Endpoints for source code access", 1, "Networking"),
    ("8.1", "Ensure AWS Batch is configured with AWS Cloudwatch Logs", 1, "Compute"),
    ("8.2", "Ensure Batch roles are configured for cross-service confused deputy prevention", 1, "Compute"),
    ("10.1", "Ensure Managed Platform updates is configured", 1, "Compute"),
    ("10.2", "Ensure Persistent logs is setup and configured to S3", 1, "Compute"),
    ("10.3", "Ensure access logs are enabled", 1, "Compute"),
    ("10.4", "Ensure that HTTPS is enabled on load balancer", 1, "Compute"),
    ("11.1", "Ensure customer-managed keys are used to encrypt AWS Fargate ephemeral storage data for Amazon ECS", 1, "Compute"),
    ("12.1", "Ensure AWS Config is Enabled for Lambda and Serverless", 1, "Compute"),
    ("12.2", "Ensure Cloudwatch Lambda insights is enabled", 1, "Compute"),
    ("12.3", "Ensure AWS Secrets manager is configured and being used by Lambda for databases", 1, "Compute"),
    ("12.4", "Ensure least privilege is used with Lambda function access", 1, "Compute"),
    ("12.5", "Ensure every Lambda function has its own IAM Role", 1, "Compute"),
    ("12.6", "Ensure Lambda functions are not exposed to everyone", 1, "Compute"),
    ("12.7", "Ensure Lambda functions are referencing active execution roles", 1, "Compute"),
    ("12.8", "Ensure that Code Signing is enabled for Lambda functions", 1, "Compute"),
    ("12.9", "Ensure there are no Lambda functions with admin privileges within your AWS account", 1, "Compute"),
    ("12.10", "Ensure Lambda functions do not allow unknown cross account access via permission policies", 1, "Compute"),
    ("12.11", "Ensure that the runtime environment versions used for your Lambda functions do not have end of support dates", 1, "Compute"),
    ("12.12", "Ensure encryption in transit is enabled for Lambda environment variables", 1, "Compute"),
    ("12.13", "Ensure Lambda layers are not shared publicly", 1, "Compute"),
    ("12.14", "Ensure Lambda recursive invocation detection is enabled", 1, "Compute"),
    ("12.15", "Ensure Lambda function URLs do not use wildcard CORS origins", 1, "Compute"),
    ("12.16", "Ensure AWS Lambda Function URLs are configured to use AWS IAM authentication", 1, "Compute"),
    ("12.17", "Ensure Lambda functions accessing private resources or sensitive data are deployed within a customer managed VPC", 1, "Compute"),
    ("16.1", "Ensure communications between your applications and clients is encrypted", 1, "Compute"),
    ("17.1", "Ensure Image Builder distribution configurations do not publicly share AMIs", 1, "Compute"),
    ("17.2", "Ensure Image Builder pipelines do not disable the built-in security cleanup script", 1, "Compute"),
    ("18.1", "Ensure ECR repositories have image scanning enabled", 1, "Compute"),
    ("18.2", "Ensure ECR repositories have lifecycle policies configured", 1, "Compute"),
    ("18.3", "Ensure ECR repositories use immutable image tags", 1, "Compute"),
    ("18.4", "Ensure private ECR repositories do not allow public access via resource policies", 1, "Compute"),
]

# Control → CheckRegistry check-id overlay, merged at score/SoA time.
CHECK_MAP: dict[str, list[str]] = {
    "2.1.5": ['compute_aws_003'],
    "2.2.1": ['compute_aws_002'],
    "2.8": ['compute_aws_001'],
    "5.4": ['network_aws_001'],
    "5.5": ['network_aws_003'],
    "12.6": ['compute_aws_004'],
}

def merge_check_map(ctrl_checks: dict[str, set]) -> None:
    """Merge CHECK_MAP into a {control_id: set(check_ids)} map, in place."""
    for ctrl, cids in CHECK_MAP.items():
        ctrl_checks.setdefault(ctrl, set()).update(cids)

def _build() -> dict[str, Any]:
    return {cid: {"title": title, "section": section, "level": level}
            for cid, title, level, section in _CONTROLS}

CIS_AWS_COMPUTE: dict[str, Any] = _build()

def _demo() -> None:
    cat = CIS_AWS_COMPUTE
    assert len(cat) == 82, len(cat)
    for ctrl in CHECK_MAP:
        assert ctrl in cat, ctrl
    print(f"cis_aws_compute_catalog self-check passed: {len(cat)} controls, "
          f"{len(CHECK_MAP)} auto-assessed")

if __name__ == "__main__":
    _demo()
