"""CIS AWS Storage Services Benchmark v1.0.0 — full control catalog (2024-07-03).


Generated by scripts/generate_cis_catalogs.py from the locally extracted
benchmark text (storage-v1.txt). Reproduce with:

    python scripts/generate_cis_catalogs.py

Only factual control identifiers, titles, profile levels and the section
tree are reproduced; CIS's copyrighted rationale/audit/remediation prose
is NOT included. Controls mapped in CHECK_MAP auto-assess from real
CheckRegistry checks; the rest surface as not_assessed (Manual).
"""

from __future__ import annotations

from typing import Any

# (control_id, title, profile_level, section). Sections match the
# platform-wide labels in compliance_mapper so aggregation stays consistent.
_CONTROLS: list[tuple[str, str, int, str]] = [
    ("1.1", "AWS Storage Backups", 1, "Storage"),
    ("1.2", "Ensure securing AWS Backups", 1, "Storage"),
    ("1.3", "Ensure to create backup template and name", 1, "Storage"),
    ("1.4", "Ensure to create AWS IAM Policies", 1, "Storage"),
    ("1.5", "Ensure to create IAM roles for Backup", 1, "Storage"),
    ("1.6", "Ensure AWS Backup with Service Linked Roles", 1, "Storage"),
    ("2.1", "Ensure creating EC2 instance with EBS", 1, "Storage"),
    ("2.2", "Ensure configuring Security Groups", 1, "Storage"),
    ("2.3", "Ensure the proper configuration of EBS storage", 1, "Storage"),
    ("2.4", "Ensure the creation of a new volume", 1, "Storage"),
    ("2.5", "Ensure creating snapshots of EBS volumes", 1, "Storage"),
    ("2.6", "Ensure Proper IAM Configuration for EC2 Instances", 1, "Identity and Access Management"),
    ("2.7", "Ensure creating IAM User", 1, "Storage"),
    ("2.8", "Ensure the Creation of IAM Groups", 1, "Storage"),
    ("2.9", "Ensure Granular Policy Creation", 1, "Storage"),
    ("2.10", "Ensure Resource Access via Tag-based Policies", 1, "Identity and Access Management"),
    ("2.11", "Ensure Secure Password Policy Implementation", 1, "Identity and Access Management"),
    ("2.12", "Ensure Monitoring EC2 and EBS with CloudWatch", 1, "Monitoring"),
    ("2.13", "Ensure creating an SNS subscription", 1, "Monitoring"),
    ("3.2", "Ensure Implementation of EFS", 1, "Storage"),
    ("3.3", "Ensure EFS and VPC Integration", 1, "Storage"),
    ("3.4", "Ensure controlling Network access to EFS Services", 1, "Storage"),
    ("3.5", "Ensure using Security Groups for VPC", 1, "Storage"),
    ("3.6", "Ensure Secure Ports", 1, "Storage"),
    ("3.7", "Ensure File-Level Access Control with Mount Targets", 1, "Storage"),
    ("3.8", "Ensure managing mount target security groups", 1, "Storage"),
    ("3.9", "Ensure using VPC endpoints - EFS", 1, "Storage"),
    ("3.10", "Ensure managing AWS EFS access points", 1, "Storage"),
    ("3.11", "Ensure accessing Points and IAM Policies", 1, "Storage"),
    ("3.12", "Ensure configuring IAM for AWS Elastic Disaster Recovery", 1, "Storage"),
    ("4.2", "Amazon Elastic File Cache", 1, "Storage"),
    ("4.3", "Ensure the creation of an FSX Bucket", 1, "Storage"),
    ("4.4", "Ensure the creation of Elastic File Cache", 1, "Storage"),
    ("4.5", "Ensure installation and configuration of Lustre Client", 1, "Storage"),
    ("4.6", "Ensure EC2 Kernel compatibility with Lustre", 1, "Storage"),
    ("4.7", "Ensure mounting FSx cache", 1, "Storage"),
    ("4.8", "Ensure exporting cache to S3", 1, "Storage"),
    ("4.9", "Ensure cleaning up FSx Resources", 1, "Storage"),
    ("5.2", "Ensure direct data addition to S3", 1, "Storage"),
    ("5.3", "Ensure Storage Classes are Configured", 1, "Storage"),
    ("6.1", "Ensure Elastic Disaster Recovery is Configured", 1, "Storage"),
    ("6.2", "Ensure AWS Disaster Recovery Configuration", 1, "Storage"),
    ("6.3", "Ensure functionality of Endpoint Detection and Response (EDR)", 1, "Storage"),
    ("6.4", "Ensure configuration of replication settings", 1, "Storage"),
    ("6.5", "Ensure proper IAM configuration for AWS Elastic Disaster Recovery", 1, "Storage"),
    ("6.6", "Ensure installation of the AWS Replication Agent", 1, "Storage"),
    ("6.7", "Ensure proper configuration of the Launch Settings", 1, "Storage"),
    ("6.8", "Ensure execution of a recovery drill", 1, "Storage"),
    ("6.9", "Ensure Continuous Disaster Recovery Operations", 1, "Storage"),
    ("6.10", "Ensure execution of a Disaster Recovery Failover", 1, "Storage"),
    ("6.11", "Ensure execution of a failback", 1, "Storage"),
    ("6.12", "Ensure CloudWatch Metrics for AWS EDR", 1, "Monitoring"),
    ("6.13", "Ensure working of EDR", 1, "Storage"),
]

# Control → CheckRegistry check-id overlay, merged at score/SoA time.
CHECK_MAP: dict[str, list[str]] = {
}

def merge_check_map(ctrl_checks: dict[str, set]) -> None:
    """Merge CHECK_MAP into a {control_id: set(check_ids)} map, in place."""
    for ctrl, cids in CHECK_MAP.items():
        ctrl_checks.setdefault(ctrl, set()).update(cids)

def _build() -> dict[str, Any]:
    return {cid: {"title": title, "section": section, "level": level}
            for cid, title, level, section in _CONTROLS}

CIS_AWS_STORAGE: dict[str, Any] = _build()

def _demo() -> None:
    cat = CIS_AWS_STORAGE
    assert len(cat) == 53, len(cat)
    for ctrl in CHECK_MAP:
        assert ctrl in cat, ctrl
    print(f"cis_aws_storage_catalog self-check passed: {len(cat)} controls, "
          f"{len(CHECK_MAP)} auto-assessed")

if __name__ == "__main__":
    _demo()
