variable "organizational_unit_id" {
  description = "AWS Organizational unit (OU) ID to deploy the StackSet to"
  type        = string
  validation {
    condition     = can(regex("^ou-[0-9a-z]{4,32}-[0-9a-z]{8,32}$|^r-[0-9a-z]{4,32}$", var.organizational_unit_id))
    error_message = "The Organizational unit (OU) ID must match the format 'ou-...' or 'r-...'."
  }
}

variable "regions" {
  description = "AWS Regions to deploy the IAM role to"
  type        = list(string)
}

variable "cloudformation_template_url" {
  description = "URL to the CloudFormation template generated by Odineyes"
  type        = string
}

variable "odineyes_api_url" {
  description = "URL of your Odineyes API (e.g. https://api.odineyes.com)"
  type        = string
}

variable "odineyes_api_key" {
  description = "API Key generated by Odineyes for auto-connecting"
  type        = string
  sensitive   = true
}

variable "odineyes_api_secret" {
  description = "API Secret generated by Odineyes for auto-connecting"
  type        = string
  sensitive   = true
}
